### ISSUE TITLE
06-data-formats-caveats: Commas and quotes exercise

### ISSUE THREAD

**Issue by gallingerj** [datacarpentry/spreadsheet-ecology-lesson#53] opened 2016-09-13 18:20 UTC
When I open species.csv from the GitHub repo in Excel 2013 (Windows), the cell contents do not appear to be enclosed in quotation marks. Furthermore, when I add a comma in "Rodent-not censused" (as per the exercise) and I save it as .csv with a different name there is no extra column error.

Looking at the species.csv file in a plain text editor, I find that the quotation marks are in fact present. So Excel is masking the quotation marks. The exercise does not work to illustrate the value of adding quotation marks because they are invisible.

**Comment by ErinBecker** [comment] 2017-04-10 22:09
@gallingerj thanks for reporting this issue. Since the problem is with one of the "extra" episodes and not a core episode, I'm going to mark this as "after-lesson-release" to indicate that it's not scheduled to be fixed before the publication of these lessons at the end of this month. 

More generally, the 06-data-formats-caveats.md lesson seems incomplete (there are a few headers with no text under them) and it seems like this file shouldn't be included in the lesson release. Is this correct @tracykteal?

**Comment by tracykteal** [comment] 2018-04-13 23:13
The ideas from 06-data-formats, including this point, was integrated into other sections, so there is no longer the 06 lesson. So, I'm going to go ahead and close this issue. Thanks so much for bringing this up.

**Closed by tracykteal** 2018-04-13 23:13 UTC
Labels: after-lesson-release, bug, moderate, technical
